apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: webrtc-app

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
